version: '3.7'

services:
  database:
    image: library/postgres:13.0-alpine
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - meta-database:/var/lib/postgresql/data
    env_file:
      - .env
  data-service:
    build:
      context: ./data-service
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
    command: java -jar app.jar
    depends_on:
      - database
    env_file:
      - .env

volumes:
  meta-database: